
---
- name: Install MongoDB 3.2
  hosts: all
  become: true
  tasks:
  - name: Add an Apt signing key to a specific keyring file
    apt_key:
      id: EA312927
      keyserver: keyserver.ubuntu.com

  - name: Add apt repository
    apt_repository:
      repo: deb [ arch=amd64,arm64 ] http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.2 multiverse
      state: present
      filename: mongodb-org-3.2

  - name: Install mongodb
    apt:
      name: mongodb-org
      update_cache: yes

  - name: Enable mongodb service
    systemd:
      name: mongod
      enabled: yes


